import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "./providers/QueryProvider";
import RecoilContextProvider from "./providers/RecoilProvider";
import  { Toaster } from 'react-hot-toast';
import 'react-material-symbols/rounded'; 
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={"font-indivisible h-screen antialiased"}> 
      <QueryProvider>
        <RecoilContextProvider>
          {children}
        </RecoilContextProvider>
        </QueryProvider>
        <Toaster />
        </body>
    </html>
  );
}
